// EvolveOS_MenuProxy - Windows 11 Modern Context Menu Handler
// Copyright (c) 2026 EvolveOS Software

#include <windows.h>
#include <shobjidl_core.h>
#include <wrl/client.h>
#include <wrl/implements.h>
#include <string>
#include <vector>
#include <fstream>
#include <shlobj.h>
#include <shlwapi.h>

#pragma comment(lib, "shlwapi.lib")

using namespace Microsoft::WRL;

// 🚀 YOUR UNIQUE CLSID
// {24E9458D-6C4C-44CD-A2F1-2AC32A7DEC73}
const GUID CLSID_EvolveOSMenu = { 0x24e9458d, 0x6c4c, 0x44cd, { 0xa2, 0xf1, 0x2a, 0xc3, 0x2a, 0x7d, 0xec, 0x73 } };

long g_cRef = 0;

// Model for our JSON items
struct MenuItem {
    std::wstring Title;
    std::wstring ExePath;
    std::wstring Arguments;
    std::wstring Icon;
    std::wstring Target;
};

// Extremely lightweight, dependency-free JSON string extractor
std::wstring ExtractJsonValue(const std::wstring& json, const std::wstring& key, size_t startPos = 0) {
    std::wstring search = L"\"" + key + L"\"";
    size_t pos = json.find(search, startPos);
    if (pos == std::wstring::npos) return L"";
    pos = json.find(L":", pos);
    if (pos == std::wstring::npos) return L"";
    size_t startQuote = json.find(L"\"", pos);
    if (startQuote == std::wstring::npos) return L"";
    size_t endQuote = json.find(L"\"", startQuote + 1);
    if (endQuote == std::wstring::npos) return L"";

    std::wstring val = json.substr(startQuote + 1, endQuote - startQuote - 1);

    // Unescape paths (C:\\Path -> C:\Path)
    size_t replacePos = 0;
    while ((replacePos = val.find(L"\\\\", replacePos)) != std::wstring::npos) {
        val.replace(replacePos, 2, L"\\");
        replacePos += 1;
    }
    return val;
}

// Reads the JSON file generated by your C# app
std::vector<MenuItem> LoadCustomItems() {
    std::vector<MenuItem> items;
    wchar_t localAppData[MAX_PATH];
    if (SUCCEEDED(SHGetFolderPathW(NULL, CSIDL_LOCAL_APPDATA, NULL, 0, localAppData))) {
        std::wstring path = std::wstring(localAppData) + L"\\EvolveOS_Optimizer\\ModernContextMenu.json";

        std::wifstream file(path);
        if (file.is_open()) {
            std::wstring content((std::istreambuf_iterator<wchar_t>(file)), std::istreambuf_iterator<wchar_t>());

            size_t pos = 0;
            while ((pos = content.find(L"{", pos)) != std::wstring::npos) {
                MenuItem item;
                item.Title = ExtractJsonValue(content, L"title", pos);
                item.ExePath = ExtractJsonValue(content, L"exePath", pos);
                item.Arguments = ExtractJsonValue(content, L"arguments", pos);
                item.Icon = ExtractJsonValue(content, L"icon", pos);
                item.Target = ExtractJsonValue(content, L"target", pos);

                if (!item.Title.empty() && !item.ExePath.empty()) {
                    items.push_back(item);
                }
                pos = content.find(L"}", pos) + 1;
            }
        }
    }
    return items;
}

// ---------------------------------------------------------
// The Explorer Command Implementation
// ---------------------------------------------------------
class CEvolveOSCommand : public RuntimeClass<RuntimeClassFlags<ClassicCom>, IExplorerCommand>
{
public:
    CEvolveOSCommand(bool isRoot, const MenuItem& item = MenuItem()) : m_isRoot(isRoot), m_item(item) {
        InterlockedIncrement(&g_cRef);
    }
    ~CEvolveOSCommand() { InterlockedDecrement(&g_cRef); }

    // IExplorerCommand
    IFACEMETHODIMP GetTitle(IShellItemArray* psiItemArray, LPWSTR* ppszName) override {
        if (m_isRoot) return SHStrDupW(L"EvolveOS Custom Actions", ppszName);
        return SHStrDupW(m_item.Title.c_str(), ppszName);
    }

    IFACEMETHODIMP GetIcon(IShellItemArray* psiItemArray, LPWSTR* ppszIcon) override {
        if (m_isRoot) {
            // Root menu icon (Extracts default app icon from EvolveOS_Optimizer.exe if in same dir)
            wchar_t modulePath[MAX_PATH];
            GetModuleFileNameW(NULL, modulePath, MAX_PATH);
            std::wstring exePath = std::wstring(modulePath);
            exePath = exePath.substr(0, exePath.find_last_of(L"\\")) + L"\\EvolveOS_Optimizer.exe";
            return SHStrDupW(exePath.c_str(), ppszIcon);
        }
        return SHStrDupW(m_item.Icon.c_str(), ppszIcon);
    }

    IFACEMETHODIMP GetToolTip(IShellItemArray* psiItemArray, LPWSTR* ppszInfotip) override { return E_NOTIMPL; }
    IFACEMETHODIMP GetCanonicalName(GUID* pguidCommandName) override { return E_NOTIMPL; }

    IFACEMETHODIMP GetState(IShellItemArray* psiItemArray, BOOL fOkToBeSlow, EXPCMDSTATE* pCmdState) override {
        *pCmdState = ECS_ENABLED;

        // Dynamic hiding logic based on C# target rules
        if (!m_isRoot && psiItemArray) {
            DWORD count = 0;
            psiItemArray->GetCount(&count);

            if (m_item.Target == L"Files" && count == 0) *pCmdState = ECS_HIDDEN;
            if (m_item.Target == L"Folders" && count == 0) *pCmdState = ECS_HIDDEN;
            if (m_item.Target == L"Background" && count > 0) *pCmdState = ECS_HIDDEN;
        }
        return S_OK;
    }

    IFACEMETHODIMP GetFlags(EXPCMDFLAGS* pFlags) override {
        *pFlags = m_isRoot ? ECF_HASSUBCOMMANDS : ECF_DEFAULT;
        return S_OK;
    }

    IFACEMETHODIMP EnumSubCommands(IEnumExplorerCommand** ppEnum) override;

    IFACEMETHODIMP Invoke(IShellItemArray* psiItemArray, IBindCtx* pbc) override {
        if (m_isRoot) return S_OK; // Root items just expand, they don't click.

        std::wstring finalArgs = m_item.Arguments;
        std::wstring targetPath = L"";

        // Try to get the file the user right-clicked on
        if (psiItemArray) {
            DWORD count = 0;
            psiItemArray->GetCount(&count);
            if (count > 0) {
                ComPtr<IShellItem> item;
                if (SUCCEEDED(psiItemArray->GetItemAt(0, &item))) {
                    LPWSTR pszName = NULL;
                    if (SUCCEEDED(item->GetDisplayName(SIGDN_FILESYSPATH, &pszName))) {
                        targetPath = pszName;
                        CoTaskMemFree(pszName);
                    }
                }
            }
        }

        // Replace "%1" in arguments with the actual file path
        size_t paramPos = finalArgs.find(L"%1");
        if (paramPos != std::wstring::npos) {
            finalArgs.replace(paramPos, 2, targetPath);
        }

        ShellExecuteW(NULL, L"open", m_item.ExePath.c_str(), finalArgs.c_str(), NULL, SW_SHOWNORMAL);
        return S_OK;
    }

private:
    bool m_isRoot;
    MenuItem m_item;
};

// Enumerator for sub-commands (Displays your custom JSON items)
class CEnumCommands : public RuntimeClass<RuntimeClassFlags<ClassicCom>, IEnumExplorerCommand>
{
public:
    CEnumCommands() : m_current(0) {
        auto jsonItems = LoadCustomItems();
        for (const auto& i : jsonItems) {
            m_items.push_back(Make<CEvolveOSCommand>(false, i));
        }
        InterlockedIncrement(&g_cRef);
    }
    ~CEnumCommands() { InterlockedDecrement(&g_cRef); }

    IFACEMETHODIMP Next(ULONG celt, IExplorerCommand** pUICommand, ULONG* pceltFetched) override {
        ULONG fetched = 0;
        for (ULONG i = 0; i < celt && m_current < m_items.size(); ++i) {
            m_items[m_current].CopyTo(&pUICommand[i]);
            m_current++;
            fetched++;
        }
        if (pceltFetched) *pceltFetched = fetched;
        return (fetched == celt) ? S_OK : S_FALSE;
    }

    IFACEMETHODIMP Skip(ULONG celt) override { m_current += celt; return S_OK; }
    IFACEMETHODIMP Reset() override { m_current = 0; return S_OK; }
    IFACEMETHODIMP Clone(IEnumExplorerCommand** ppenum) override { return E_NOTIMPL; }

private:
    std::vector<ComPtr<IExplorerCommand>> m_items;
    size_t m_current;
};

IFACEMETHODIMP CEvolveOSCommand::EnumSubCommands(IEnumExplorerCommand** ppEnum) {
    if (m_isRoot) {
        *ppEnum = Make<CEnumCommands>().Detach();
        return S_OK;
    }
    *ppEnum = nullptr;
    return S_FALSE;
}

// ---------------------------------------------------------
// Standard COM Class Factory Boilerplate
// ---------------------------------------------------------
class CEvolveOSClassFactory : public IClassFactory
{
public:
    IFACEMETHODIMP QueryInterface(REFIID riid, void** ppv) override {
        if (riid == IID_IUnknown || riid == IID_IClassFactory) { *ppv = this; return S_OK; }
        *ppv = NULL; return E_NOINTERFACE;
    }
    IFACEMETHODIMP_(ULONG) AddRef() override { return 2; }
    IFACEMETHODIMP_(ULONG) Release() override { return 1; }

    IFACEMETHODIMP CreateInstance(IUnknown* pUnkOuter, REFIID riid, void** ppv) override {
        if (pUnkOuter != NULL) return CLASS_E_NOAGGREGATION;
        auto command = Make<CEvolveOSCommand>(true);
        return command->QueryInterface(riid, ppv);
    }
    IFACEMETHODIMP LockServer(BOOL fLock) override { return S_OK; }
};

STDAPI DllGetClassObject(REFIID rclsid, REFIID riid, void** ppv) {
    if (rclsid == CLSID_EvolveOSMenu) {
        CEvolveOSClassFactory factory;
        return factory.QueryInterface(riid, ppv);
    }
    return CLASS_E_CLASSNOTAVAILABLE;
}

STDAPI DllCanUnloadNow() {
    return g_cRef == 0 ? S_OK : S_FALSE;
}

BOOL APIENTRY DllMain(HMODULE hModule, DWORD  ul_reason_for_call, LPVOID lpReserved) {
    return TRUE;
}